name: Code Quality

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: 📦 Install ruff
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b

      - name: 📝 Format Code
        run: ruff format --check

      - name: 🔍 Lint Code
        run: ruff check

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: 🔭 Install UV
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
        with:
          activate-environment: 'true'

      - name: 🔄 Sync Dependencies
        run: uv sync

      - name: 🔍 Type Check
        run: pyrefly check --output-format=github
